[package]
name = "utilitarios"
version = "1.6.0"
edition = "2018"
license = "mit"
readme = "README.md"
# Tal pacote data desta vers√£o, 2019 acho?!
rust-version = "1.40"
repository = "https://github.com/patrick7star/rust-utilitarios"

[profile.dev]
opt-level=0
